apiVersion: v2
name: cluster-crds
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: traefik-crds
    version: 1.13.*
    repository: https://traefik.github.io/charts