argo-cd:
  global:
    domain: argocd.test.local
  configs:
    params:
      server.insecure: true
    secret:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
        sealedsecrets.bitnami.com/managed: "true"
