apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  project: "default"
  source:
    repoURL: https://github.com/lexi-blanchet/k3s-lab-apps.git
    targetRevision: dev
    path: apps/argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true