apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-infra
  annotations:
    "helm.sh/hook": post-install
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements: 
      {{ .Values.repos.infra | toYaml | nindent 6 | trim }}
  template:
    metadata:
      name: "{{`{{.Values.chartName}}`}}"
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "{{`{{ .Values.syncWave | quote }}`}}"
    spec:
      project: "default"
      source:
        repoURL: "{{`{{.Values.repoURL | quote }}`}}"
        targetRevision: "{{`{{.Values.revision}}`}}"
        path: "{{`{{.Values.path}}`}}"
      destination:
        server: "{{`{{.Values.server}}`}}"
        namespace: "{{`{{.Values.chartName}}`}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: false
          selfHeal: true
