apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-infra
  namespace: argo-cd
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements: 
      - chartName: cert-manager
        repoURL: https://github.com/lexi-blanchet/k3s-lab-apps.git
        path: apps/infra/cert-manager
        revision: dev-rancher
        syncWave: 1
        server: https://kubernetes.default.svc
      - chartName: traefik
        repoURL: https://github.com/lexi-blanchet/k3s-lab-apps.git
        path: apps/infra/traefik
        revision: dev-rancher
        syncWave: 2
        server: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{`{{.chartName}}`}}"
      namespace: argo-cd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "{{`{{ .syncWave | quote }}`}}"
    spec:
      project: "default"
      source:
        repoURL: "{{`{{.repoURL}}`}}"
        targetRevision: "{{`{{.revision}}`}}"
        path: "{{`{{.path}}`}}"
      destination:
        server: "{{`{{.server}}`}}"
        namespace: "{{`{{.chartName}}`}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
