apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-infra
  namespace: {{ .Values.argocdNamespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements: 
      - chartName: sealed-secrets
        namespace: kube-system
        repoURL: https://github.com/lexi-blanchet/k3s-lab-apps.git
        path: apps/infra/sealed-secrets
        revision: {{ .Values.defaultTargetRevision }}
        syncWave: 0 # Needs to go first so we can seed secrets properly
        server: https://kubernetes.default.svc
      - chartName: cert-manager
        namespace: cert-manager
        repoURL: https://github.com/lexi-blanchet/k3s-lab-apps.git
        path: apps/infra/cert-manager
        revision: {{ .Values.defaultTargetRevision }}
        syncWave: 1
        server: https://kubernetes.default.svc
      - chartName: traefik
        namespace: traefik
        repoURL: https://github.com/lexi-blanchet/k3s-lab-apps.git
        path: apps/infra/traefik
        revision: {{ .Values.defaultTargetRevision }}
        syncWave: 2
        server: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{`{{.chartName}}`}}"
      namespace: {{ .Values.argocdNamespace }}
      annotations:
        argocd.argoproj.io/sync-wave: "{{`{{ .syncWave | quote }}`}}"
    spec:
      project: "default"
      source:
        repoURL: "{{`{{.repoURL}}`}}"
        targetRevision: "{{`{{.revision}}`}}"
        path: "{{`{{.path}}`}}"
        helm:
          skipCrds: true # We don't want these managed by helm so we can self-install and avoid annoying race conditions
      destination:
        server: "{{`{{.server}}`}}"
        namespace: "{{`{{ .namespace }}`}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
