apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "99"
    "argocd.argoproj.io/sync-options": Prune=false # Don't delete the source of truth
    "argocd.argoproj.io/sync-wave": "99"
spec:
  project: "default"
  source:
    repoURL: https://github.com/lexi-blanchet/k3s-lab-apps.git
    targetRevision: dev-rancher
    path: apps/infra/argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true # Avoid race condition so we can actually bootstrap
    automated:
      prune: false
      selfHeal: true