apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "99"
spec:
  project: "default"
  source:
    repoURL: https://github.com/lexi-blanchet/k3s-lab-apps.git
    targetRevision: main
    path: apps/infra/argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true