---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argo-cd
spec:
  encryptedData:
    admin.password: AgCESnGAvBaXVgMUJLBlJZYRo9JcpuyE8t6IjKy1Ma8zkVony6EA+09HGSjqX1t8cnWRMFCQFGbDUfnpwgPv68wucM1oR2gEXjzDv6YqKEFN1KPGOqDGhHEir988jNF+3YRVMsxG1fX7KXbLszh+wn5wIAgvlDyW/JZE6O+QpQvFT5D6VukOAUm2R5pK80sWPoUBXQxXrM2m8SMUK4xSP/l9tPQAC0hEjPBeLQm3xb/0toVDqVNeKrjdNe2pZqbOshJjapFyp0xwP+KqbajlmpqkmfRuq+ZsKfWyg1ygi3YcHOibi/R3n2k9Z6EJy8gTtloipchz/V8KPi9MCqmY0wWOFKS/x5xaJ8vVbvsRYWr6hDJho1vlrS+p0322RpO+X2foNIPa8Bdy73Ci87JxU3539uAxstXhZWLhj6RaSP4K1vkk+VI/5ZNdwxnypma6mi2M0cKq3fI7yh8m3wyDO6qUU/3OjmBuYCCOsPSddm24Uk6qirvFICxxTQP8KJ3N+LiT0z82n1+dTrkrc6rdNxQa19SVDd8AdbA7gIR1Qm6HK13zLSpwtyHLJLUIgAHXfFH/mOOPnqxeVJmcZeNx2+wqVfoiMr4A5LOQf+VFpAnXcCVnD3aHgTuJ5O8ytHD7xFcjL6ZIKtAQXgCpEpySJdDJxVADW8Ou5Zye/r1DEJzRabuhsAvu+jAtEe3sxi2yXZMARS59G7kO6tbVDfM+kUnuoByb+ARmGjVEBVFrJ6R1jcXtEwzhkfpBLcJWJ25BE6vNjYYP7SnFooTk5v0=
    admin.passwordMtime: AgBF+0rbfD5nbXrD7OLymN9wdmApB3SJuXV5MIuy0U7PMv35thdYj0q4KgmAh0EzYj27XUKWWFsJ7v55wYyqnao0+WipZOsifNafHIQVqv8jnAucA0aASaPLukH/JPefuw2HcNJ14d7plzqQRLeAyJbwcMMMOk5lehlkXOvdjzYpKcP0uDhdcqHdjG2ZE7HZu/ARtcmj4+8LugD26yLKXxWhF+tLP+A6bosaqBsP20fvoEEJhoe+wy9IZca/JQ1p25xXR/lHLfDeqdzLJs56ja9lmXTh7Mguzoyhtj0ahwJO2x19Fpzu2aJ9NXCG84exl8BkK4YYhaeu+41eApAJqvbJ7sPaRFBrVAncjrPi7npg4Cb8uIJ55AY6wBnrliAfqvXvkZ+B9MaN+UCZL+6hPMaNW0hRHdzNlLv9y3kW0A+g5nARJJpvR4HBJmrMoC3/iz4ypLCVRExHJ0hQ/+bPIuOCWvVmBClUlyoRLUdhAxJxO5O9YH+H5leODREor78ZA7QqzskJHqo8Gq3mA9aYfg9WJUy1u4rnEr9PplGgO39vKo9f9L+VR6+By1vrIXqiILD8W1Rvy5VzEZmLPcIfRXsEEfNWfMEcA5/3Q1kGJ25/BEDLP2P/CmIZCN9SWS2Q3c5TTjhVw7ImG3LlpDkcTvAq62pso7shHk/EqSD1wBkb0x5oEaG9S3JJFfSsb7DAkJzuuB8x/64DXoWQ5md4LDTIgqd5gQ==
  template:
    metadata:
      name: argocd-secret
    type: Opaque
